[quick_lookup_window]
inner_size = {width= 780,height= 495}
[quick_lookup_window.source_code]
js_iife_bundle_file_path="quick-lookup/build/bundle.js"
css_file_path="quick-lookup/build/bundle.css"

[[layers]]
id = "first-level-step-1"
[layers.switches]
right_upper_south = {on_click = {keyboard = {key = "A"}}}
right_upper_east = {on_click = {keyboard = {key = "O"}}}
right_upper_north = {on_click = {keyboard = {key = "I"}}}
right_upper_west = {on_click = {keyboard = {key = "N"}}}
left_upper_north = {on_click = {keyboard = {key = "T"}}}
left_upper_south = {on_click = {keyboard = {key = "E"}}}
left_upper_east = {on_click = {keyboard = {key = "H"}}}
left_upper_west = {on_click = {keyboard = {key = "R"}}}
left_lower_north = {on_click = {keyboard = {key = "t"}}}
left_lower_south = {on_click = {keyboard = {key = "e"}}}
left_lower_west = {on_click = {keyboard = {key = "r"}}}
left_lower_east = {on_click = {keyboard = {key = "h"}}}
right_lower_north = {on_click = {keyboard = {key = "i"}}}
right_lower_south = {on_click = {keyboard = {key = "a"}}}
right_lower_west = {on_click = {keyboard = {key = "n"}}}
right_lower_east = {on_click = {keyboard = {key = "o"}}}
left_trigger_2 = {on_click = {show_quick_lookup_window_on_hold = {}}}
right_trigger_2 = {on_click = {visit_layer="shortcuts-level"}}

[layers.switches.left_trigger]
on_click = {visit_layer="first-level-step-3"}
on_double_click = {move_to_or_visit_layer="second-level-step-1"}

[layers.switches.right_trigger]
on_click = {visit_layer="first-level-step-2"}
on_double_click = {move_to_or_visit_layer="second-level-step-1"}

[[layers]]
id = "first-level-step-3"
[layers.switches]
right_upper_south = {on_click = {keyboard = {key = "B"}}}
right_upper_east = {on_click = {keyboard = {key = "Return"}}}
right_upper_north = {on_click = {keyboard = {key = "K"}}}
right_upper_west = {on_click = {keyboard = {key = "G"}}}
left_upper_north = {on_click = {keyboard = {key = "L"}}}
left_upper_south = {on_click = {keyboard = {key = "D"}}}
left_upper_west = {on_click = {keyboard = {key = "Escape"}}}
left_upper_east = {on_click = {keyboard = {key = "P"}}}
left_lower_north = {on_click = {keyboard = {key = "l"}}}
left_lower_south = {on_click = {keyboard = {key = "d"}}}
left_lower_west = {on_click = {keyboard = {key = "Backspace"}}}
left_lower_east = {on_click = {keyboard = {key = "p"}}}
right_lower_north = {on_click = {keyboard = {key = "k"}}}
right_lower_south = {on_click = {keyboard = {key = "b"}}}
right_lower_west = {on_click = {keyboard = {key = "g"}}}
right_lower_east = {on_click = {keyboard = {key = "Space"}}}
left_trigger_2 = {on_click = {show_quick_lookup_window_on_hold = {}}}
right_trigger_2 = {on_click = {visit_layer="shortcuts-level"}}

[layers.switches.right_trigger]
on_click = {visit_layer="first-level-step-4"}

[[layers]]
id = "first-level-step-2"
[layers.switches]
right_upper_south = {on_click = {keyboard = {key = "V"}}}
right_upper_east = {on_click = {keyboard = {key = "F"}}}
right_upper_north = {on_click = {keyboard = {key = "Y"}}}
right_upper_west = {on_click = {keyboard = {key = "M"}}}
left_upper_north = {on_click = {keyboard = {key = "W"}}}
left_upper_south = {on_click = {keyboard = {key = "S"}}}
left_upper_west = {on_click = {keyboard = {key = "U"}}}
left_upper_east = {on_click = {keyboard = {key = "C"}}}
left_lower_north = {on_click = {keyboard = {key = "w"}}}
left_lower_south = {on_click = {keyboard = {key = "s"}}}
left_lower_west = {on_click = {keyboard = {key = "u"}}}
left_lower_east = {on_click = {keyboard = {key = "c"}}}
right_lower_north = {on_click = {keyboard = {key = "y"}}}
right_lower_south = {on_click = {keyboard = {key = "v"}}}
right_lower_west = {on_click = {keyboard = {key = "m"}}}
right_lower_east = {on_click = {keyboard = {key = "f"}}}
left_trigger_2 = {on_click = {show_quick_lookup_window_on_hold = {}}}
right_trigger_2 = {on_click = {visit_layer="shortcuts-level"}}

[layers.switches.left_trigger]
on_click = {visit_layer="first-level-step-4"}


[[layers]]
id = "first-level-step-4"
[layers.switches]
right_upper_east = {on_click = {keyboard = {key = "X"}}}
right_upper_north = {on_click = {keyboard = {key = "Q"}}}
left_upper_north = {on_click = {keyboard = {key = "Z"}}}
left_upper_west = {on_click = {keyboard = {key = "J"}}}
left_lower_north = {on_click = {keyboard = {key = "z"}}}
left_lower_west = {on_click = {keyboard = {key = "j"}}}
right_lower_north = {on_click = {keyboard = {key = "q"}}}
right_lower_east = {on_click = {keyboard = {key = "x"}}}
left_trigger_2 = {on_click = {show_quick_lookup_window_on_hold = {}}}
right_trigger_2 = {on_click = {visit_layer="shortcuts-level"}}
right_upper_south = {on_click = {toggle_quick_lookup_window = {}}}


[[layers]]
id = "second-level-step-1"
[layers.switches]
right_upper_north = {on_click= {mouse= {button= "Middle"}}}
right_upper_south = {on_click= {mouse= {button= "Left"}}}
right_upper_east = {on_click= {mouse= {button= "Right"}}}
right_upper_west = {on_click= {boost_mouse_cursor_by_multiplier=5}}
left_upper_north = {on_click = {keyboard = {key = "UpArrow"}}}
left_upper_south = {on_click = {keyboard = {key = "DownArrow"}}}
left_upper_west = {on_click = {keyboard = {key = "LeftArrow"}}}
left_upper_east = {on_click = {keyboard = {key = "RightArrow"}}}
left_trigger_2 = {on_click = {show_quick_lookup_window_on_hold = {}}}
right_trigger_2 = {on_click = {visit_layer="shortcuts-level"}}

[layers.cardinal_levers]
left_stick = {control_mouse_cursor={}}
right_stick = {control_mouse_scrollwheel={}}
[layers.switches.left_trigger]
on_click = {visit_layer="second-level-step-3"}
on_double_click = {move_to_or_visit_layer="first-level-step-1"}
[layers.switches.right_trigger]
on_click = {visit_layer="second-level-step-2"}
on_double_click = {move_to_or_visit_layer="first-level-step-1"}

[[layers]]
id = "second-level-step-3"
[layers.switches]
right_upper_south = {on_click = {keyboard = {key = "&"}}}
right_upper_east = {on_click = {keyboard = {key = "^"}}}
right_upper_north = {on_click = {keyboard = {key = "%"}}}
right_upper_west = {on_click = {keyboard = {key = "*"}}}
left_upper_north = {on_click = {keyboard = {key = "!"}}}
left_upper_south = {on_click = {keyboard = {key = "#"}}}
left_upper_west = {on_click = {keyboard = {key = "$"}}}
left_upper_east = {on_click = {keyboard = {key = "@"}}}
left_lower_north = {on_click = {keyboard = {key = "1"}}}
left_lower_south = {on_click = {keyboard = {key = "3"}}}
left_lower_west = {on_click = {keyboard = {key = "4"}}}
left_lower_east = {on_click = {keyboard = {key = "2"}}}
right_lower_north = {on_click = {keyboard = {key = "5"}}}
right_lower_south = {on_click = {keyboard = {key = "7"}}}
right_lower_west = {on_click = {keyboard = {key = "8"}}}
right_lower_east = {on_click = {keyboard = {key = "6"}}}
left_trigger_2 = {on_click = {show_quick_lookup_window_on_hold = {}}}
right_trigger_2 = {on_click = {visit_layer="shortcuts-level"}}

[layers.switches.right_trigger]
on_click = {visit_layer="second-level-step-4"}

[[layers]]
id = "second-level-step-2"
[layers.switches]
right_upper_south = {on_click = {keyboard = {key = "}"}}}
right_upper_east = {on_click = {keyboard = {key = ":"}}}
right_upper_north = {on_click = {keyboard = {key = "\""}}}
right_upper_west = {on_click = {keyboard = {key = "{"}}}
left_upper_north = {on_click = {keyboard = {key = "("}}}
left_upper_south = {on_click = {keyboard = {key = ">"}}}
left_upper_west = {on_click = {keyboard = {key = "<"}}}
left_upper_east = {on_click = {keyboard = {key = "("}}}
left_lower_north = {on_click = {keyboard = {key = "9"}}}
left_lower_south = {on_click = {keyboard = {key = "."}}}
left_lower_west = {on_click = {keyboard = {key = ","}}}
left_lower_east = {on_click = {keyboard = {key = "0"}}}
right_lower_north = {on_click = {keyboard = {key = "'"}}}
right_lower_south = {on_click = {keyboard = {key = "]"}}}
right_lower_west = {on_click = {keyboard = {key = "["}}}
right_lower_east = {on_click = {keyboard = {key = ";"}}}
left_trigger_2 = {on_click = {show_quick_lookup_window_on_hold = {}}}
right_trigger_2 = {on_click = {visit_layer="shortcuts-level"}}

[layers.switches.left_trigger]
on_click = {visit_layer="second-level-step-4"}

[[layers]]
id = "second-level-step-4"
[layers.switches]
right_upper_east = {on_click = {keyboard = {key = "|"}}}
right_upper_north = {on_click = {keyboard = {key = "Tab", modifiers=["Shift"]}}}
left_upper_north = {on_click = {keyboard = {key = "_"}}}
left_upper_south = {on_click = {keyboard = {key = "+"}}}
left_upper_west = {on_click = {keyboard = {key = "~"}}}
left_upper_east = {on_click = {keyboard = {key = "?"}}}
left_lower_north = {on_click = {keyboard = {key = "-"}}}
left_lower_south = {on_click = {keyboard = {key = "="}}}
left_lower_west = {on_click = {keyboard = {key = "`"}}}
left_lower_east = {on_click = {keyboard = {key = "/"}}}
right_lower_north = {on_click = {keyboard = {key = "Tab"}}}
right_lower_east = {on_click = {keyboard = {key = "\\"}}}
left_trigger_2 = {on_click = {show_quick_lookup_window_on_hold = {}}}
right_trigger_2 = {on_click = {visit_layer="shortcuts-level"}}
right_upper_south = {on_click = {toggle_quick_lookup_window = {}}}

[[layers]]
id = "shortcuts-level"
[layers.switches]
right_upper_south = {on_click = {keyboard = {key = "v", modifiers=["Control"]}}}
right_upper_east = {on_click = {keyboard = {key = "c", modifiers=["Control"]}}}
right_upper_north = {on_click = {keyboard = {key = "a", modifiers=["Control"]}}}
right_upper_west = {on_click = {keyboard = {key = "x", modifiers=["Control"]}}}
left_upper_east = {on_click = {keyboard = {key = "z", modifiers=["Shift","Control"]}}}
left_upper_west = {on_click = {keyboard = {key = "z", modifiers=["Control"]}}}
left_trigger_2 = {on_click = {show_quick_lookup_window_on_hold = {}}}
